### ISSUE TITLE
Error with porting the visualization of "Generalized ROC curve metrics for several combinations"

### ISSUE THREAD

**Issue by nhintruong** [tdhock/max-generalized-auc#4]
I am facing an issue while I am working on porting the visualization of the [Generalized ROC curve metrics for several combinations ](https://github.com/tdhock/max-generalized-auc/blob/102bce9771dfddd61e7c9e0dc52e00037b1f3e65/figure-neuroblastomaProcessed-combinations-interactive.R)source code. Here is the screenshot of the error :
![figure-neuroblastomaProcessed-combinations-interactive error](https://github.com/tdhock/max-generalized-auc/assets/102540257/697f9c02-0739-4165-aebd-175c3f16d46e)
@tdhock It looks like the roc.dt variable is missing two data columns, FPR and TPR. Could you please check for the missing in this file data or let me know where I might find them?
Thank you very much for your time and assistance.

**Comment by tdhock** [comment]
I just fixed this by removing a `[[1]]` https://github.com/tdhock/max-generalized-auc/commit/bea87ddde10bedf0dd3b9fd2f371ba708eb67e26
and I made a few other tweaks involving figure size, panel spacing, text abbreviations, so that the text labels can be read.
I published the updated viz, added it to my fork, and submitted a PR to the main animint gallery, https://github.com/animint/gallery/pull/8
